### ISSUE TITLE
Example(s) not displaying 

### ISSUE THREAD

**Issue by Boardbreak** [polyrhythm-project/rds-scores#109]
Hello @craigsapp and @epoudrier , 

I went to add group attributions to examples that I had already done a 2nd round of proofreading to and found that several examples are broken/formatting has gone wild. Particularly R572, R573, R574, R582, R588 and R602; though I've noticed a few others as well. The kern data is correct (from what I can tell) and the examples were displaying fine when I originally worked on them/uploaded them to GitHub a week ago. I've included a screenshot of R572 for reference. Any idea as to what's causing this? Is it an external VHV issue?

![Screenshot (182)](https://user-images.githubusercontent.com/59404234/96533132-2c947380-1242-11eb-9a26-afc0a241d32f.png)

**Comment by epoudrier** [comment]
@craigsapp Here the list of examples that are confirmed to have VHV issues, some of which are caused by the converter: 129
198
222
237B
281
371
389
573
574
588

**Comment by epoudrier** [comment]
Issue fixed

**Comment by epoudrier** [comment]
Issue fixed.
